### ISSUE TITLE
Automatic Test Specification Creation by betelgeuse

### ISSUE THREAD

**Issue by amsharma3** [SatelliteQE/betelgeuse#100]
Currently RHDS team is creating Test Specification in Polarion manually.

In our case, we create a test plan for each RFE/feature, and we add all the test case for that feature as work items to the test plan document.
Can we please modify betelgeuse to create such test plans automatically from command line, so that it can create all the headers as Scope, Purpose, Setup etc in a Polarion document(test plan)?

**Comment by elyezer** [comment]
@amsharma3 do you map each RFE/feature as being a Requirement?

I am looking for a way to identify what are the test cases related to an RFE so Betelgeuse can create that for you.

**Comment by amsharma3** [comment]
@elyezer That is true, we map each RFE as a Requirement.
The workflow is like this (which we follow) -
1. Release Plan
2. Requirement Document - (which will have all the RFEs mapped to it as work items)
3. Test Specification Document for each RFE (feature) - which will have all the test cases mapped to it as work items
4. Then Test run

**Comment by elyezer** [comment]
Talked with @amsharma3 and we came up with this RST file format for the Test Specification document:

```rst
:title:
:id:
:link: 

Title 1
=======

Paragraph 1

Paragraph 2

Sub Title
---------

Paragraph 1

Test Cases
==========

# Linking from a python module or package

.. link-python: tests.my_feature

# Link using test case field values

.. link-test-case: id=<someid>

.. link-test-case: feature=<some feature>

.. link-test-case: <field>=<field_value>
```

**Comment by elyezer** [comment]
Betelgeuse dropped pylarion dependency and only generates XML files to the importers. Since we don't have an importer to help creating the test specification we can close this issue.

In case we happen to have the test specification importer in the future we can either reopen this issue or create a new one.
