### ISSUE TITLE
We should be able to pass some tokens (Requirement,CaseLevel, CaseImportance, TestType, etc.) through command line

### ISSUE THREAD

**Issue by amsharma3** [SatelliteQE/betelgeuse#105]
Requirement, CaseLevel, CaseImportance, TestType, etc. Tokens can be passed for all tests by default without specifying them in the python source code.

**Comment by elyezer** [comment]
One should be able to specify default values for fields if it is not defined on the source code when running `betelgeuse test-case` command.

The current field value resolution order is shown below. The first found is used.

1. Test Case
2. Class
3. Module
4. Package

It will be changed in the way if that field is not available in any of those levels it will check for the default value and will use it if defined.

**Comment by elyezer** [comment]
Instead of accepting the default value from the command line now betelgeuse accepts a config module which allows the default values to be defined. Also functions can be used in order to generate the default value which gives the users more power when configuring it.
