### ISSUE TITLE
Please add Requirement and Automation Script fields to be used by Betelgeuse Configuration Module

### ISSUE THREAD

**Issue by amsharma3** [SatelliteQE/betelgeuse#106]
Hello,

Great functionality added in betelgeuse recently -  Betelgeuse Configuration Module. Excellent work!
I would like to use "Requirement" and "Automation Script" fields to be used in Config module for betelgeuse. Can you please add them in the list of custom fields. So, That I can put them in config module.

Thanks,
Amita

**Comment by elyezer** [comment]
I've got the changes to support the requested feature merged but I will only release it when #107 is resolved so I can include both on the 0.12 release.
