### ISSUE TITLE
Document a list of custom fields and its values - IDs in Polarion

### ISSUE THREAD

**Issue by amsharma3** [SatelliteQE/betelgeuse#109]
It is really hard to dig into the Polarion and it also needs admin access to find out the the real custom IDs of fields and values to use them with in Config Module file for Betelgeuse Configuration Module feature.

It will be helpful to have them listed somewhere in a document or some readme file.
Thanks,
Amita

**Comment by elyezer** [comment]
The custom fields and their enumerations are documented by the DOC-998663 on Mojo. Instead of duplicating that information and possibly getting outdated here, I think it will be better to reference people to it.

**Comment by elyezer** [comment]
Reading the Mojo doc again I realized that there are some custom field enumerations that are not supposed to be customized per project. That said, I went ahead and documented only those field values.
