### ISSUE TITLE
Request to parse multiple lines for fields like "title" in docstrings

### ISSUE THREAD

**Issue by mrniranjan** [SatelliteQE/betelgeuse#112]
Fields like "title" where test case title is described sometimes are long (more than 80) and fail certain pep8 checks, So request to support .title be parsed when specified in multiple lines

Example: 
:Title: Testsuite:Testfeature: verify user with more Ad use uid more than 80 characters
is able to login to RHEL Atomic Host

**Comment by elyezer** [comment]
@mrniranjan  that is already possible, the issues is that you probably are not using the indentation that RST requires. Check this gist https://gist.github.com/elyezer/2932ac864172210578d46324bada3f53 so you can how it will be rendered and click on the `Raw` button to see how it is on the source code.

**Comment by elyezer** [comment]
I am going to close this issue. Feel free to reopen or create a new one if the formatting is not the issue.
