### ISSUE TITLE
Make Betelgeuse Python 3.6+ only

### ISSUE THREAD

**Issue by elyezer** [SatelliteQE/betelgeuse#113]
I am opening this issue to collect usage and plan when Betelgeuse will be Python 3.6+ only.

The only dependency that Betelgeuse has that blocks it to be py3 only is pylarion which is py2 only, Betelgeuse code base should be py3 already or will require minimum changes though.

That said, the plan will be to drop pylarion as dependency and with that the commands  `test-plan` and `requirement` will be gone. But the benefit is that Betelgeuse will be able to take advantage of new Python's features such as the asyncio which will make faster to collect test cases and parse large jUnit files.

Also Python 2.7 won't be maintained anymore past 2020 https://pythonclock.org/.

Have in mind that you can always install an old version of Betelgeuse if you need Python 2 support when the migration happens but I highly recommend you taking time and consider upgrading your code to Python 3 and using all the great features that the new version offers.

**Comment by abalakh** [comment]
Ping. Are there any updates?

`robottelo` is py3 only (and some time ago @omaciel asked to explicitly remove all workarounds for backwards compatibility), but we can't really use new py3 features like, for example, f-strings as otherwise parsing for betelgeuse will fail, so we can't fully use py3 until this issue is resolved.

**Comment by elyezer** [comment]
@abalakh this can be done now but will remove any compatibility with Pylarion since it won't be updated. This was not done before because of the dependency on Pylarion.

**Comment by spoore1** [comment]
Can you fork or branch a python3 only version?  or better yet, maybe create a legacy branch with pylarion?

**Comment by elyezer** [comment]
I would love to do that. I will do ASAP this week.

**Comment by elyezer** [comment]
Here is the plan that I will be putting in place:

* Drop pylarion requirement
* Update Betelgeuse to be Python 3.6+ only
* Make any command that depended on Pylarion to show a message saying that is not available anymore and it will be removed.

With all that I will be releasing version 1.0.0 and then later on 1.1 will drop the commands that depended on Pylarion. How does this sound @abalakh @spoore1? Any concerns?

**Comment by spoore1** [comment]
Sure, that sounds good to me.

**Comment by elyezer** [comment]
Here are the changes that I am planning to merge https://github.com/SatelliteQE/betelgeuse/pull/120. Feel free to provide any feedback.
