### ISSUE TITLE
pylarion now supporting python 3

### ISSUE THREAD

**Issue by mirekdlugosz** [SatelliteQE/betelgeuse#121]
An email came hour ago announcing that pylarion now supports Python 3. Everything that was removed during 2 -> 3 transition can be most likely brought back, maybe with slight changes.

**Comment by elyezer** [comment]
The requirements management was the important feature that was dropped but now an importer is available for it.

That said, I don't have plans to bring pylarion usage to Betelgeuse. I would invest time implementing the requirements XML feature which is lacking in the current version.

**Comment by elyezer** [comment]
Requirement command is now added by https://github.com/SatelliteQE/betelgeuse/pull/127 and the test-plan command is removed by https://github.com/SatelliteQE/betelgeuse/pull/129. With that there is no need to bring pylarion back and we can avoid having a dependency on a private project.
