### ISSUE TITLE
Make sure that Test Cases set some specific fields

### ISSUE THREAD

**Issue by omaciel** [SatelliteQE/betelgeuse#24]
Whether creating for the first time or updating existing `Test Cases`, the following fields should be set:
- [x] Title - Short description of the test case
- [x] Status - (defaults to `DRAFT` but other acceptable values are `PROPOSED`, `NEEDS UPDATE`, `APPROVED` and `INACTIVE`)
- [x] Test Type - (defaults to `FUNCTIONAL` but other acceptable values are `NON-FUNCTIONAL` and `STRUCTURAL`)
- [x] Subtype 1 - More specific selection for certain types. (defaults to `-`)
- [x] Pos/Neg - Set this to indicate if the test is a positive or negative style test . (defaults to `POSITIVE` but other acceptable values are `NEGATIVE`)
- [x] Importance- This field should have been imported from TCMS. (defaults to `MEDIUM` but other acceptable values are `LOW,`HIGH`and`CRITICAL`)
- [x] Level - Set the level of the test based on the definitions here.Test Types, Levels, and Importance (defaults to `COMPONENT` but other acceptable values are `INTEGRATION`, `SYSTEM`and `ACCEPTANCE`)
- [x] Automation- Acceptable values are `AUTOMATED`, `MANUAL ONLY`, `NOT AUTOMATED`

As you can see, `Betelgeuse` already sets these fields but some of the defaults values used need to be flexible to allow for more flexibility.

For the time being, specially for the **Satellite 6 QE** team, the following rules should be used:
- Status: `DRAFT` as we want to be able to automatically update them whenever the docstring changes. If we were to set the `Status` to any other value, updating a `Test Case` would require several steps to change the `Status` back to `DRAFT`.
- Pos/Neg: Since all of our tests use a nomenclature similar to `test_positive/negative_*`, we should use this information when importing/updating `Test Cases`
- Automation: We currently rely on `Testimony` flag found in the docstring to determine whether something is automated or not.

No changes required for the other fields for now.

**Comment by elyezer** [comment]
Closing this in favor of the new required fields.
