### ISSUE TITLE
Set some custom fields when creating Test Runs

### ISSUE THREAD

**Issue by omaciel** [SatelliteQE/betelgeuse#28]
When we create a new Test Run, let's set the following custom fields:
- Automated: True
- Arch: x86_64
- Variant: Server
- Build: Satellite x.y.z Compose n - OS version

![screenshot 2016-02-18 09 20 50](https://cloud.githubusercontent.com/assets/53362/13145859/fec77d6a-d620-11e5-9f87-c06c8bb042da.png)

**Comment by elyezer** [comment]
We need OS to be added to the list of custom fields. I have a code for these options already.

**Comment by elyezer** [comment]
Automated flag is already added, currently missing:
- [ ] Arch
- [ ] Variant
- [ ] Build

**Comment by elyezer** [comment]
The above variables are custom fields. That said it may differ from one project to the other and a generic way of passing that information should be created.

For example one possible solution is to expect `--custom-fields` option that can be specified multiple times and expect a `key=value` format or even a JSON dict like `{"isautomated": true, "arch": "x86_64"}`. The later will ensure custom field type and also the parsed information will be passed directly to the TestRun creation.

**Comment by omaciel** [comment]
Agreed with the `--custom-fields` option as it will allow anyone to pass whatever values that want. Obviously it would be up to the user to pass valid values ;)
