### ISSUE TITLE
Need support for adding test setup

### ISSUE THREAD

**Issue by Akasurde** [SatelliteQE/betelgeuse#32]
Would love to see if we can update test setup in Polarion using betelgeuse

**Comment by amsharma3** [comment]
Betelgeuse is currently taking the docstring from test cases and putting that into the description field of Polarion. It will be nice if all the information in docstring can go to the specific field ::

For Example :

```
@Feature: Replication

@Setup: Four masters, replication is configured

@Steps:

1. Install four instances of Directory Server on same host i.e. M1, M2, M3, M4
2. Configure two way replcation between all instances.
3. Add a test user in M1.
4. Verify all the masters M2, M3 and M4 have that test user added.

@Assert: All masters should be in sync.

@Status: Manual
```

Steps should go in Test Steps and Assert should go in expected result.

**Comment by elyezer** [comment]
This is already implemented.
