### ISSUE TITLE
Add testcases to existing requirements

### ISSUE THREAD

**Issue by Akasurde** [SatelliteQE/betelgeuse#43]
Betelgeuse should support adding testcases to existing requirements available on Polarion.

**Comment by omaciel** [comment]
Thank you @Akasurde We will try to work on this issue this Friday.

**Comment by Akasurde** [comment]
@omaciel I would love to work on this issue. Let me know if I can help you in this.

**Comment by omaciel** [comment]
@Akasurde sure thing, your help will be greatly appreciated

**Comment by elyezer** [comment]
ea9c94504d3d68010b25a6d970fe50a3c5981cdc introduces the ability of defining a Requirement for each test method, test case class or test module. Just specify `@requirement` and use a already created requirement name or if no requirement is found then betelgeuse will create one.
