### ISSUE TITLE
Description contains all tags

### ISSUE THREAD

**Issue by Akasurde** [SatelliteQE/betelgeuse#44]
Currently betelgeuse adds docstring into description of testcase. Instead, it should only add testcase description in Polarion.

![screenshot from 2016-06-06 16-32-57](https://cloud.githubusercontent.com/assets/633765/15820064/78bdf02a-2c04-11e6-87b1-830fd34a4320.png)

**Comment by omaciel** [comment]
Thank you @Akasurde We will try to work on this issue this Friday.

**Comment by Akasurde** [comment]
@omaciel I would like to work on this issue. Let me know if I can help you with this.

**Comment by omaciel** [comment]
@Akasurde sure thing, your help will be greatly appreciated

**Comment by elyezer** [comment]
@Akasurde the issue is all yours. I have assigned you to it.
