### ISSUE TITLE
Test Runs created by Betelgeuse should set the `isautomated` flag to True

### ISSUE THREAD

**Issue by omaciel** [SatelliteQE/betelgeuse#51]
Since `Test Runs` created by Betelgeuse are populated with data from automated test runs, it makes sense to set the `isautomated` attribute to `True`. Perhaps this should be an option (default to `False`?) passed to the `test-run` method?

**Comment by elyezer** [comment]
Betelgeuse test-run expects a jUnit XML report which is supposed to be created from a test suite run. I think that it can have the default of True giving that. And have the option to set to false if it is an especial case.

**Comment by omaciel** [comment]
This should be of help:

``` python
my_tr = TestRun.create('<product-id>', '<testrun-id>', '<template>', **{'isautomated': True})
```
