### ISSUE TITLE
Need an option to specify the token mark for example use :...: instead of @...:

### ISSUE THREAD

**Issue by amsharma3** [SatelliteQE/betelgeuse#54]
It will be great if I can use :...: instead of @....: in my source code file for betelgeuse.

For example the following docstring:

``` python
"""My test

@requirement: My Requirement
@steps: Do this
@expectedresults: Expected result
"""
```

Would be like this:

``` python
"""My test

:requirement: My Requirement
:steps: Do this
:expectedresults: Expected result
"""
```

**Comment by sthirugn** [comment]
This is more of a testimony enhancement and is nothing to do with betelgeuse.  I believe the part of the code which handles is the regex - https://github.com/SatelliteQE/testimony/blob/master/testimony/parser.py#L7

**Comment by elyezer** [comment]
@sthirugn we have two options here. One is make Betelgeuse configure the Testimony regex depending on the option it receives, and the other is to make both adapt to the token prefix.

I am in favor of improving both, what do you think?

This issue will be closed when the token prefix is able to be specified.

**Comment by sthirugn** [comment]
I agree with the approach of fixing both.  This will be a great improvement for both the tools.

**Comment by elyezer** [comment]
Depends on https://github.com/SatelliteQE/testimony/issues/108
