### ISSUE TITLE
Using the @title token for polarion test case title

### ISSUE THREAD

**Issue by spoore1** [SatelliteQE/betelgeuse#65]
Can we have the option (via command line arg) to use the test case Test token for the polarion test case title on import?

I would like to use this instead of using the python module, class, method/function names.

**Comment by sthirugn** [comment]
Can you please explain the use case by showing the command that you are trying to use?

**Comment by spoore1** [comment]
Well, I hadn't actually started running it for this particular query yet. 

Here's an example though:

```
# cat test_simple.py 
class TestExample(object):
    def test_case_0001(self):
        """ Test Case 0001
        @casecomponent: ipa
        @Setup:
        1. Install OS
        @Steps:
        1. Run something one time
        @Assert:
        1. something works
        """
        pass

```

Then I run this:

```
# betelgeuse test-case --collect-only --path test_simple.py <project>
Creating test case test_case_0001 for requirement: Simple.
Linking test case test_case_0001 to requirement: Simple.
```

I'm looking for a way to tell betelgeuse to use "Test Case 0001" for the test case title in polarion instead of test_case_0001.

So, I was thinking something like:

```
# betelgeuse test-case --use-test-name --collect-only --path test_simple.py <project>
Creating test case "Test Case 0001" for requirement: Simple.
Linking test case "Test Case 0001" to requirement: Simple.
```

**Comment by elyezer** [comment]
I think a good solution would be to add an option that allows you specify a polarion field to be mapped to the first line of the docstring. This way we have the flexibility of defining what to map for the first line.

Worth mention that it will only grab the first line not the first paragraph. On the Betelgeuse code this will be checked before assigning any token, so if the field is present on the docstring as a token it will be overridden.

**Comment by spoore1** [comment]
That would work.  And like you said would allow more flexibility since I think some people use Description similar to how my team uses Title.

One thing, though.  I thought testimony used the first line of docstring as Test now.  Are you suggesting that change too?

**Comment by elyezer** [comment]
Short answer, yes.

Long answer, Testimony currently does use the first line as test, but a new option should be added to it since one may not pass the `test` as being a valid token, currently it will be bypassed and the `test` token will be created.

**Comment by elyezer** [comment]
I've opened https://github.com/SatelliteQE/testimony/issues/118 to fix on testimony and then bring to Betelgeuse

**Comment by elyezer** [comment]
In order to follow all other token definitions Betelgeuse should support a `@title` token and fill the title if that token is present on the docstring or use the function/method name.

**Comment by spoore1** [comment]
Thanks guys!

**Comment by elyezer** [comment]
@spoore1 thank you for the feature request, it is good to have control over the title.
