### ISSUE TITLE
test case steps and expectedresults missing

### ISSUE THREAD

**Issue by spoore1** [SatelliteQE/betelgeuse#79]
I'm able to create new test cases and link to an existing requirement but, I'm no longer seeing the steps and expected results.

I'm using similar to this:

```
class TestClass(object):
    def test_case_0001(self):
        """
        @Title:  Some new test case title
        @Description:   
        @Requirement: Some Existing Requirement    
        @caselevel: Acceptance
        @casecomponent: ipa
        @setup:
        1. Setup1
        2. Setup2
        3. Setup3

        @steps:
        1. Step1

        @expectedresults:
        1. Result1
        """

```

betelgeuse --token-prefix "@" test-case --path /root/test_suite_dir/test_cases.py RedHatEnterpriseLinux7

**Comment by spoore1** [comment]
FYI, I discovered that the issue seemed to be using single and double quotes in the steps.  I modified the steps to remove those and everything seemed to work as expected.

**Comment by omaciel** [comment]
@spoore1 perhaps we should do some sanitation around this area?

**Comment by elyezer** [comment]
@spoore1 if you can paste one step that was failing we can investigate and see how Betelgeuse can be improved.

**Comment by spoore1** [comment]
This was one of the steps I had that wasn't showing up:

```
    1. ipa idoverrideuser-mod 'default trust view' user@ad.domain --desc="new description"
```

**Comment by elyezer** [comment]
@spoore1 that is because the `@` character on the steps. There is a known bug on testimony (https://github.com/SatelliteQE/testimony/issues/120) that prevents the same character used as the token prefix on the value of a token.

I will close this issue in favor of the testimony one.

**Comment by spoore1** [comment]
Ah, ok, I thought the quotes were causing the issue.  I didn't think about the @ in the user/principal name.

Thanks
