### ISSUE TITLE
Add tests and coverage information for the project

### ISSUE THREAD

**Issue by omaciel** [SatelliteQE/betelgeuse#8]
We need to write tests for Betelgeuse.

**Comment by elyezer** [comment]
:+1:

**Comment by elyezer** [comment]
Testing betelgeuse on travis will be hard since pylarion is not public available. For more info check: https://travis-ci.org/SatelliteQE/betelgeuse/builds/96028707

**Comment by elyezer** [comment]
I was able to work around this issue by creating https://github.com/elyezer/fake_pylarion which is a fake package that offers all required imports.

**Comment by sthirugn** [comment]
@elyezer how many imports/functions we talking? Can we use mock for testing?

**Comment by elyezer** [comment]
@sthirugn even though we will be using mock, we need to import the betelgeuse module in order to test its functions. There is no other way to handle that since we need to call the real betelgeuse functions.

**Comment by elyezer** [comment]
Even though the test coverage status is being reported on README I will close this when I get a decent coverage number.

**Comment by sthirugn** [comment]
@elyezer ty for explanation.
