### ISSUE TITLE
Add test case `UUID` to generated xunit files

### ISSUE THREAD

**Issue by omaciel** [SatelliteQE/betelgeuse#80]
# Reference

Please read our MOJO **DOC-1073077**.
## Request

Given a `xunit` file, create a new method to parse through the source code for automated tests, and update the XML file to include the test case UUID for each test found. For example, given the following (snippet) xunit file:

``` xml
<?xml version="1.0" encoding="utf-8"?><testsuite errors="3" failures="2" name="pytest" skips="0" tests="3" time="4157.148">
<testcase classname="tests.foreman.api.test_syncplan.SyncPlanSynchronizeTestCase" file="tests/foreman/api/test_syncplan.py" line="609" name="test_positive_synchronize_custom_product_future_sync_date" time="981.63787818">
```

The new method should look at the source code for the test named `test_positive_synchronize_custom_product_future_sync_date` in the file `tests/foreman/api/test_syncplan.py` and extract the `uuid` from it.

Once this information is made available, we would then generate a brand new xml file containing the `uuid` as part of a new `<properties><property>` block:

``` xml
<?xml version="1.0" encoding="utf-8"?>
<testsuites>
    <properties>
        <property name="polarion-testrun-title" value="TITLE_GOES_HERE" />  
        <property name="polarion-project-id" value="PROJECT_ID_GOES_HERE"/>  
        <property name="polarion-user-id" value="USER_ID_GOES_HERE"/>  
        <property name="polarion-lookup-method" value="custom"/>  
    </properties>  
    <testsuite errors="3" failures="2" name="pytest" skips="0" tests="3" time="4157.148">
        <testcase classname="tests.foreman.api.test_syncplan.SyncPlanSynchronizeTestCase" file="tests/foreman/api/test_syncplan.py" line="609" name="test_positive_synchronize_custom_product_future_sync_date" time="981.63787818">
        <properties> 
            <property name="polarion-testcase-id" value="0495cb39-2f15-4b6e-9828-1e9517c5c826"/> 
        </properties> 
    </testcase>
</testsuites>
```
## Specification

As you an see, this new method should accept the following arguments:
- `xunit_file` - this should be the path to the original xunit file as generated by your automation process
- `polarion_user_id` - your Polarion username
- `polarion_project_id` - your projects's ID (e.g. RHSAT6)
- `polarion_testrun_name` - The title for your `TestRun` (e.g. "Satellite 6.2.0 SNAP 1.0 - RHEL 7")

**Comment by elyezer** [comment]
Thank you, I will make sure this issue gets worked on the next iteration.

**Comment by omaciel** [comment]
@elyezer how is this task coming along?

**Comment by elyezer** [comment]
@omaciel it is planned to be delivered tomorrow. I mean the change on the repo, the release that will include it may happen probably on next week.

**Comment by omaciel** [comment]
@elyezer got an update for me?
