### ISSUE TITLE
Drop token-prefix option

### ISSUE THREAD

**Issue by elyezer** [SatelliteQE/betelgeuse#92]
https://github.com/SatelliteQE/testimony/pull/123 drops the token-prefix in favor of field-list RST syntax. Betelgeuse should reflect that change by dropping its token-prefix option too.

Whis issue should be worked and the testimony version must be pinned to at least the version where the token prefix is going to be dropped.

**Comment by spoore1** [comment]
Without token-prefix (and using a character other than colon), is it possible to use colons in the value side of the `:key:` part of the RST field list syntax?  I thought that was part of the reason the token-prefix option was added originally.

**Comment by elyezer** [comment]
@spoore1 you can have `:` on the value. The prefix was added because the desire to support RST's field-list which 1) produces better docs and 2) does not look like Java annotations.

The prefix was added as a feature to help migrating and allowing new code to start using the RST's field-list while giving some time to old code to get updated.

**Comment by spoore1** [comment]
@elyezer I'm seeing issues using : in the value field.  For instance if I use a url in description, I see nothing get imported but, if I strip off http: , I do see the rest get imported:

Does not seem to work:

    :description: http://something.gitrepo.test/some/path

Seems to work:

    :description: something.gitrepo.test/some/path

Should I open this as a separate bug?

**Comment by elyezer** [comment]
@spoore1 I checked and it is really not parsing properly:

```
In [5]: parser = DocstringParser()

In [8]: parser.parse("""
   ...: :description: http://test.com/path/to/something
   ...: """)
Out[8]: ({}, {})

In [10]: parser.parse("""
    ...: :description:
    ...:     http//test.com/path/to/something
    ...: """)
Out[10]: ({}, {'description': 'http//test.com/path/to/something'})
```

The parser is implemented by Testimony, I have tried using testimony and added some print to see if the generated XML (which testimony uses to extract the information) is working. And as we can see:

```
In [4]: parser.parse("""
   ...: :description: http://test.com/path/to/something
   ...: """)
b'<?xml version="1.0" encoding="utf-8"?>\n<!DOCTYPE document PUBLIC "+//IDN docutils.sourceforge.net//DTD Docutils Generic//EN//XML" "http://docutils.sourceforge.net/docs/ref/docutils.dtd">\n<!-- Generated by Docutils 0.12 -->\n<document source="&lt;string&gt;"><docinfo><field><field_name>description</field_name><field_body><paragraph><reference refuri="http://test.com/path/to/something">http://test.com/path/to/something</reference></paragraph></field_body></field></docinfo></document>'
Out[4]: ({}, {})
```

It is working but the logic to check for steps is making that break https://github.com/SatelliteQE/testimony/blob/master/testimony/parser.py#L67-L75. Will do some more investigation and will try to fix this asap.

If you want create an issue to track this down, then I will recommend you to open on testimony project instead. I will do that if you don't do before I start working on it.

Thank you

**Comment by elyezer** [comment]
Token prefix was done by ec38bdde5543abd41b9c17dae3a1c6c974cc7fc4, closing this.
