### ISSUE TITLE
support reading docstrings from conftest.py

### ISSUE THREAD

**Issue by spoore1** [SatelliteQE/betelgeuse#97]
Is it possible to have betelgeuse also read a tests conftest.py file if it exists and the path is a directory that contains a conftest py file?

```
`[root@ipa1 betelgeuse_testcase_importer]# cat test2/conftest.py
""" 
:requirement: IPA Feature 0001
:caselevel: Acceptance
:casecomponent: ipa
:caseautomation: Automated
:caseimportance: Medium
:testtype: Functional
:description: some default description
"""

import pytest

[root@ipa1 betelgeuse_testcase_importer]# cat test2/test_0001.py 
class TestFeature(object):
    def test_feature_command_with_option_a(self):
        """
        :title: IPA - Feature command run with option A
        :id: ipa_test_feature_command_with_option_a

        :setup: Prepare environment with servers and users
        :steps:
        1. step 1
        2. step 2
        :expectedresults:
        1. pass
        2. pass
        """
        option = "A"
        assert option == "A"

    def test_feature_command_with_option_b(self):
        """
        :title: IPA - Feature command run with option B
        :id: ipa_test_feature_command_with_option_b

        :setup: Prepare environment with servers and users
        :steps:
        1. step 1
        2. step 2
        :expectedresults:
        1. pass
        2. pass
        """
        option = "B"
        assert option == "B"

[root@ipa1 betelgeuse_testcase_importer]# betelgeuse test-case --path ./test2/ PROJECT

```

Thanks,
Scott

**Comment by elyezer** [comment]
Is the idea here of having project globals?

We already have context for module, classes and test methods. Adding support for conftest will open for requiring adding package level contexts. We can have that, but the focus right now is to deliver xml-test-case command. That said, if you want to contribute with a patch that would be awesome.

All the test collection and parsing is provided by Testimony and this function (https://github.com/SatelliteQE/testimony/blob/master/testimony/__init__.py#L58-L60) is the one that adds rules to select a test module. In addition to that will be required to update how the contexts are handled so we can add more levels.

If we have conftest and package context which one should be considered as more generic? I think the answer would be conftest, which will follow this hierarchy: conftest, then package, then module, then class and finally test method.

**Comment by spoore1** [comment]
Eleyezer,

The idea is kinda of like project globals I guess.  I have started adding certain labels to the docstrings for my modules if they would be identical for all methods in the class(es) in the file.  Just a way to simplify what goes into each function/method docstring.  Effectively treating them like module level globals.  Thus, I guess this would be a package (or directory) level global.

Sure, I'll take a look at writing a patch for this request.  Should I open a separate issue in testimony?

As for order of priority for the context levels,  I would have thought package then conftest.  TBH my initial thought was super simple just add conftest.py support like any other module.  Then just require defining in only one place or you could get strange results.  Can't you have multiple directories with different conftests in a single package?

package/__init.py
package/dir1/{conftest.py, test_feature1.py}
package/dir2/{conftest.py, test_feature2.py}

Also, you're thinking the package level contexts should be included in __init__.py right?

Thanks,
Scott

**Comment by elyezer** [comment]
I am not sure if multiple conftest.py can exist inside the same package. If we decide on supporting multiple conftest we need to improve even more the contexts so conftest higher in the directory tree will be used if in a subdirectory does not have one, else the subdirectory will override the more generic one. Thinking a little bit more about that, I think we should only support package level context and don't support conftest at all. Package context will help on have globals and that is more suited for every test runner.

Yes, package level should analyze the `__init__.py` docstring.

**Comment by spoore1** [comment]
I guess this depends on test coding style.  You can have multiple conftest.py files in a directory tree that isn't necessarily a python package.  Each conftest.py applies to the tests in its own directory.  For example,  my team simply installs our tests from git and executes py.test command.   We have test "suites" as separate directories with separate conftest.py files.

As for order of precedence,  the conftest in the subdirectory "should" override the one in a parent directory I think.  The data closest to the test should be the most "authoritative", right?   At least in how we're talking about processing docstrings?

That is still a good point about having to maintain parent directory conftest data to fully support that.  Maybe just `__init__.py` is right for the start.  I think that's definitely the easier path.  There is no sub-directory/child-node type inheritance expected there right?  Even if groups aren't using packages, they could add `__init__.py` files to directories to supply directory level defaults for their test modules.

My first draft was for conftest but, I'll modify for `__init__` and go from there.  If we decide to include conftest later, it can be added separately, I think.

**Comment by elyezer** [comment]
Either way is fine to me, subpackages inherit tokens from parent packages or only the modules within a package inherit from its `__init__.py` file.

About conftest, yes I agree that having package context will open even more the possibilities, then we can check if supporting conftest will continue being required.

**Comment by spoore1** [comment]
I didn't realize this one was still open.  I think it can be closed now right?  We just support the __init__.py docstrings instead of the conftest ones I originally suggested right?

**Comment by elyezer** [comment]
@spoore1 yeah we can close this. Thank you!
