### ISSUE TITLE
Test Cases must provide new automation_script field

### ISSUE THREAD

**Issue by omaciel** [SatelliteQE/betelgeuse#98]
Test Cases in Polarion now require the following field to be set: `automation_script`

This field will store a `URL` pointing to the location of the specific test case in the source code. Though one can provide a generic URL such as `https://github.com/SatelliteQE/robottelo`, we should be able to provide something more accurate such as `https://github.com/SatelliteQE/robottelo/blob/master/tests/foreman/cli/test_contentview.py#L160`.

**Comment by elyezer** [comment]
If the AST can provide the module path like `tests/foreman/cli/test_contentview.py` and the line number where the testcase is defined then we could expect an `automation_script_url` option and the path + line number can be added after the URL.

Or offer some formatting like `{path}` and `{line_number}` so one can specify the URL based on the source control management. For example git web would have an URL like `http://<hostname>/git/users/<user>/<project>/tree/dirsrvtests/{path}?h=tp_fix#n{line_number}` while github would have `https://github.com/<user>/<project>/blob/master/{path}#L{line_number}`

**Comment by omaciel** [comment]
@elyezer agreed and I think the module (full) path and file number is provided by AST, but I could be wrong. This should be optional.
