### ISSUE TITLE
Test Cases must provide the approvee field

### ISSUE THREAD

**Issue by omaciel** [SatelliteQE/betelgeuse#99]
Polarion now requires that `Test Cases` should provide the `approvee` field. I think that we can use the user running the script to populate this field at runtime.

**IMPORTANT**: the user running the script **must** have the `project_approver` role in order to be able to approve a `Test Case`.

Here's an example:

```python
testcase = TestCase(project_id='RHSAT6', work_item_id='RHSAT6-2726')
testcase.add_approvee('omaciel')
testcase.update()
testcase.edit_approval('omaciel', 'approved')
```

**Comment by elyezer** [comment]
I think it should have an `approvee` on each docstring and then if not set use the user information or require a default-approvee option.

**Comment by omaciel** [comment]
@elyezer as long as it is optional, I'm good with the proposal. It is assumed that the `approvee` will have the proper permission in Polarion, so we need to make sure to handle issues when this is not true (and provide a friendly message to the user)

**Comment by elyezer** [comment]
@omaciel does it make sense to have more than one approvee? I mean if a test case is already created and approved, and a new aprovee is passed it should be added or replace or do not change?

**Comment by omaciel** [comment]
I am almost 100% sure that you can have multiple approvees.

⁣Sent from my phone​

**Comment by elyezer** [comment]
Implementing this I saw that it is able to `add_approvee` but not `remove_approvee`. I can also edit an approval to say disapproved.

With that said, if the `approvees` token is filled with one or more approvees separated by comma then they will be added and the test case approved. But if that is removed I am not sure what action to take, disapprove the approval? (that is the only action that Pylarion seems to support currently).

**Comment by elyezer** [comment]
Same as test case status, was decided that approvee will be automatically set to the first returned user by the `get_allowed_approvers` test case method, and the approval status changed to `approved`.
